'use strict'

export const SET_ROUND_ORDER = 'SET_ROUND_ORDER'
export const QUEUE_NEXT_ROUND = 'QUEUE_NEXT_ROUND'
export const DECREMENT_TIMER = 'DECREMENT_TIMER'
export const TOGGLE_COUNTING_DOWN = 'TOGGLE_COUNTING_DOWN'
export const SET_SHOULD_SCORE_EMOTION = 'SET_SHOULD_SCORE_EMOTION'
export const SET_COUNTING_DOWN = 'SET_COUNTING_DOWN'
export const SAVE_FACE_TO_EMOTION = 'SAVE_FACE_TO_EMOTION'

export const SCORE_EMOTION_REQUEST = 'SCORE_EMOTION_REQUEST'
export const SCORE_EMOTION_SUCCESS = 'SCORE_EMOTION_SUCCESS'
export const SCORE_EMOTION_FAILURE = 'SCORE_EMOTION_FAILURE'

export const TOGGLE_DEMO_MODE = 'TOGGLE_DEMO_MODE'
export const SET_ALERT = 'SET_ALERT'

export const SET_CANVAS_RECT = 'SET_CANVAS_RECT'
export const SET_VIDEO_SIZE = 'SET_VIDEO_SIZE'

export const HIDE_FLASH = 'HIDE_FLASH'

export const SET_VIDEO_SRC_RECT = 'SET_VIDEO_SRC_RECT'
